### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by netgfx** [freshOS/Router#1]
Hello,

I followed the instructions from the README but I can't seem to get this to work, do we need to attach each viewController to the other via storyboards? (I think not since this is the issue this class is trying to solve right?)

So I have `Router.default.navigate(MyNavigation.video, from: PageType.MainAudioPage.viewController)`

since `navigate(.video)` doesn't seem to work

And I have an initial ViewController which calls another stub (not associated with any other VC via segue) ViewController
I have added both of them on the myNavigation struct.

But nil nothing happens.

Any ideas?

Swift 4 Btw

**Comment by pfarinav** [comment]
Did you add the extension for UIVIewController?

**Comment by netgfx** [comment]
Solved it. The was an issue with the view not being a ViewController but a subclass of `View` once I added the parent ViewController the problem was solved.

**Comment by s4cha** [comment]
@netgfx Glad you were able to fix it :)
