### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dunyakirkali** [freshOS/Router#2]

**Comment by s4cha** [comment]
@dunyakirkali It has not been "maintained" for a while but the current version should work fine.
Are you experiencing any issue?

**Comment by dunyakirkali** [comment]
Not really.
I wanted to give `Router` a try on Swift 4 and saw that there was a branch for it which was last updated 10 months ago so I was curious.

**Comment by s4cha** [comment]
We got pretty busy on the other freshOS repos lately but we're willing to keep supporting every project :)
