### ISSUE TITLE
Manage Delegate among ViewControllers

### ISSUE THREAD

**Issue by AbrahamEP** [freshOS/Router#3]
How can I manage the delegate reference? Can you give me an example? Thanks

**Comment by s4cha** [comment]
@AbrahamEP you could pass the delegate as a param in the enum case, example: 

```swift
enum YPNavigation: Navigation {
    case gallery(photo: Photo, delegate: GalleryDelegate?)
}
```
Closing this as this project has been deprecated. Don't hesitate to reach out if you have any questions.
