### ISSUE TITLE
Use Router to handle url scheme

### ISSUE THREAD

**Issue by gianpispi** [freshOS/Router#4]
Morning,

Is it possible to use Router with URL Scheme? I mean go directly to a View controller from the App Delegate.

Thank you!

**Comment by FlixMa** [comment]
Im interested in this too.

**Comment by s4cha** [comment]
@giapispi, this has never been supported unfortunately.
Closing this as this project has been deprecated in favour of Native Flow controllers / Coordinator pattern.
Don't hesitate to reach out if you have any questions :)
